include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.generated.dart'
    - '**/*.json.dart'

dart_code_metrics:
  rules:
    - prefer-conditional-expressions
