targets:
  $default:
    builders:
      freezed:
        options:
          format: false
          map: false
          when: false
        generate_for:
          include:
            - lib/models/*.dart
            - lib/models/**/*.dart
            - lib/src/rust/**/*.dart
            - lib/views/photo_booth_screen/theme/*.dart
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/models/*.dart
            - lib/models/**/*.dart
      mobx_codegen:mobx_generator:
        generate_for:
            - lib/managers/*.dart
            - lib/views/**/*_view_model.dart
      widgetbook_generator:use_case_builder:
        generate_for:
            - lib/views/**/*.dart
      widgetbook_generator:telemetry:
        enabled: false
