name: flutter_rust_bridge_example
description: A new Flutter project.

publish_to: "none"
version: 0.0.18+18

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  fluent_ui: ^4.4.1

  # MVC
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5

  # Models
  freezed_annotation: ^2.1.0

  # Interop
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.71.1

  # Misc
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # MVC
  mobx_codegen: ^2.1.1

  # Code quality
  flutter_lints: ^2.0.1

  # Models
  freezed: ^2.2.0

  # Code generation
  build_runner: ^2.2.0
  ffigen: ^7.2.9

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
