name: momento_booth
description: Opensource photobooth application

publish_to: "none"
version: 0.7.2+85

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # UI
  auto_size_text: 3.0.0
  fluent_ui: 4.8.6
  go_router: 13.2.2
  flutter_svg: 2.0.10+1
  animated_text_kit: 4.2.2
  figma_squircle: 0.5.3
  flutter_scroll_shadow: 1.2.4
  flutter_layout_grid: 2.0.6
  pretty_qr_code: 3.3.0
  confetti: 0.7.0
  wave: 0.2.2
  texture_rgba_renderer:
    git: https://github.com/h3x4d3c1m4l/flutter_texture_rgba_renderer
  lottie: 3.1.0
  font_awesome_flutter: 10.7.0
  smooth_scroll_multiplatform: 1.0.8
  widgetbook: 3.7.1
  widgetbook_annotation: 3.1.0
  flex_color_picker: 3.4.1

  # Printscreen/Image processing
  screenshot: 2.3.0
  image: 4.1.7

  # MVC
  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1

  # Models
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # Rust library/Interop
  rust_lib_momento_booth:
    path: rust_builder
  ffi: 2.1.2
  flutter_rust_bridge: 2.0.0-dev.30

  # Printing
  printing: 5.12.0
  pdf: 3.10.8

  # System
  path_provider: 2.1.2
  path: ^1.9.0
  window_manager: 0.3.8
  file_selector: 1.0.3
  win32: 5.4.0

  # Log and error handling
  loggy: 2.0.3
  flutter_loggy: 2.0.2
  sentry_flutter: 7.18.0

  # Sound output
  just_audio: 0.9.37
  just_audio_windows: 0.2.0
  just_audio_mpv: 0.1.7

  # Misc
  meta: ^1.11.0
  toml: 0.15.0
  synchronized: 3.1.0+1
  collection: 1.18.0
  mqtt5_client: 4.2.2
  dart_casing: 3.0.1
  package_info_plus: 5.0.1
  lemberfpsmonitor: 0.0.3+6
  crypto: 3.0.3
  draggable_scrollbar: 0.1.0
  csslib: 1.0.0

dev_dependencies:
  # UI
  widgetbook_generator: 3.7.0

  # MVC
  mobx_codegen: 2.6.1

  # Code quality
  flutter_lints: 3.0.2

  # Models
  freezed: 2.5.0
  json_serializable: 6.7.1

  # Code generation
  build_runner: 2.4.9
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/bitmap/
    - assets/svg/
    - assets/fonts/brandon_grotesque/
    - assets/scripts/
    - assets/sounds/

  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/brandon_grotesque/Brandon_light.otf
          weight: 300

scripts:
  run: rps install all && rps generate all
  install:
    all: rps install flutter && rps install cargo-expand && rps install flutter_rust_bridge_codegen && rps install deps
    flutter: fvm install
    cargo-expand: cargo install cargo-expand
    flutter_rust_bridge_codegen: cargo install flutter_rust_bridge_codegen --version 2.0.0-dev.30
    deps: fvm flutter pub get
  clean:
    rust_bridge: git clean -xfd lib/src
  generate:
    all: rps generate l10n && rps generate rust_bridge
    l10n: fvm flutter gen-l10n
    rust_bridge: rps clean rust_bridge && flutter_rust_bridge_codegen generate
    build_runner_targets: fvm dart run build_runner build --delete-conflicting-outputs
  update:
    rust-install: rustup update
  docs:
    install-deps: cargo install mdbook mdbook-mermaid mdbook-admonish
    build:
      $before: $docs install-deps
      $script: mdbook build documentation
