name: momento_booth
description: Opensource photobooth application

publish_to: "none"
version: 0.0.30+30

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  auto_size_text: 3.0.0
  fluent_ui: 4.5.0
  go_router: 6.5.8
  flutter_svg: 2.0.5
  animated_text_kit: 4.2.2
  hotkey_manager: 0.1.7
  flutter_scroll_shadow: 1.2.0
  flutter_layout_grid: 2.0.1
  pretty_qr_code: 2.0.3

  # Printscreen/Image processing
  screenshot: 1.3.0
  image: 4.0.15

  # MVC
  mobx: 2.1.4
  flutter_mobx: 2.0.6+5

  # Models
  freezed_annotation: 2.2.0
  json_annotation: 4.8.0

  # Interop
  ffi: 2.0.1
  flutter_rust_bridge: 1.75.1

  # Printing
  printing: 5.10.3
  pdf: 3.10.1

  # System
  path_provider: 2.0.14
  path: 1.8.2
  window_manager: 0.3.2

  # Misc
  meta: 1.8.0
  toml: 0.14.0
  file_picker: 5.2.10
  confetti: 0.7.0
  loggy: 2.0.3
  flutter_loggy: 2.0.2
  synchronized: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # MVC
  mobx_codegen: 2.2.0

  # Code quality
  flutter_lints: 2.0.1

  # Models
  freezed: 2.3.2
  json_serializable: 6.6.1

  # Code generation
  build_runner: 2.3.3
  ffigen: 7.2.10

flutter:
  uses-material-design: true

  assets:
    - assets/bitmap/
    - assets/svg/
    - assets/fonts/brandon_grotesque/

  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/brandon_grotesque/Brandon_light.otf
          weight: 300
  