[package]
name = "flutter_rust_bridge_example"
version = "0.1.0"
edition = "2021"

[lib]
name = "flutter_rust_bridge_example"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.69"
flutter_rust_bridge = "1.72.2"
num = "0.4"
image = "0.24.3"
crossbeam = "0.8"
