[package]
name = "flutter_rust_bridge_example"
version = "0.1.0"
edition = "2021"

[lib]
name = "flutter_rust_bridge_example"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "flutter_rust_bridge_example_debug_bin"
path = "src/main.rs"

[target.'cfg(unix)'.dependencies]
gphoto2 = "3.2.0"

[dependencies]
derive_more = "0.99.17"
once_cell = "1.17.1"
atom_table = "1.1.0"
anyhow = "1.0.69"
flutter_rust_bridge = "1.72.2"
num = "0.4"
image = "0.24.3"
crossbeam = "0.8"
ffsend-api = "0.7.3"
nokhwa-bindings-macos = "0.2.0"
nokhwa = { version = "0.10.3", features = ["input-native", "output-threaded"] }

# Patch for https://github.com/l1npengtul/nokhwa/issues/98

[patch.crates-io]
nokhwa-bindings-macos = { path = './target/patch/nokhwa-bindings-macos-0.2.0' }

[package.metadata.patch.nokhwa-bindings-macos]
version = "0.2.0"
patches = [
    { path = "nokhwa-fix-issue-98.patch", source = "GithubPrDiff" }
]