[package]
name = "flutter_rust_bridge_example"
version = "0.1.0"
edition = "2021"

[lib]
name = "flutter_rust_bridge_example"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "flutter_rust_bridge_example_debug_bin"
path = "src/main.rs"

[target.'cfg(unix)'.dependencies]
gphoto2 = "3.2.0"

[dependencies]
anyhow = "1.0.69"
flutter_rust_bridge = "1.72.2"
num = "0.4"
image = "0.24.3"
crossbeam = "0.8"

[dependencies.nokhwa]
version = "0.10.3"
features = ["input-native", "output-threaded"]
