name: Deploy docs to GitHub Pages

env:
  MDBOOK_VERSION: "0.4.32"
  BOOK_LOCATION: "documentation"

on:
  push:
    branches: [main]
    paths: [documentation/**]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: deploy-documentation
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    name: Build and Deploy

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: ${{ env.MDBOOK_VERSION }}

      - name: Build static site
        run: mdbook build ${{ env.BOOK_LOCATION }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BOOK_LOCATION }}/book
