name: PR CI

on:
  pull_request:
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: "pr-ci"
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Detect Flutter Version
      uses: kuhnroyal/flutter-fvm-config-action@v1

    - name: Setup Flutter
      uses: hrishikesh-kadam/setup-flutter@v1
      with:
        ref: ${{ env.FLUTTER_VERSION }}
        setFlutterRootPath: 'true'
        addPubCacheBinToPath: 'true'
        flutterPrecache: '--windows'

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-libgphoto2 mingw-w64-x86_64-pkgconf mingw-w64-x86_64-gcc mingw-w64-x86_64-clang
        path-type: inherit
        release: true

    - name: Install minimal Rust
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-pc-windows-gnu
        profile: minimal
        toolchain: stable-gnu
        components: rustfmt, clippy
        default: true

    - name: Setup Rust build cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rust -> target"
      
    - name: Install flutter_rust_bridge_codegen
      uses: baptiste0928/cargo-install@v1
      with:
        crate: flutter_rust_bridge_codegen
        version: "1.78.0"

    - name: Install Dependencies
      run: flutter packages get

    - name: Generation l10n
      run: flutter gen-l10n

    - name: Generate Dart-to-Rust bridging code
      run: >
        flutter_rust_bridge_codegen
        --rust-input rust/src/dart_bridge/api.rs
        --dart-output lib/rust_bridge/library_api.generated.dart
        --rust-output rust/src/dart_bridge/ffi_exports.rs
        --skip-add-mod-to-lib --no-build-runner
      
    - name: Run Code Generation
      run: flutter pub run build_runner build --delete-conflicting-outputs
      
    - name: Flutter Analyze
      run: flutter analyze

    - name: Build Project
      run: msys2 -c 'flutter build windows --release'
    
    - name: Bundle DLL dependencies of the helper library
      run: curl https://raw.githubusercontent.com/h3x4d3c1m4l/mingw-bundledlls/master/mingw-bundledlls | python - --copy build\windows\runner\Release\momento_booth_native_helpers.dll
